import type { Metadata } from 'next';
import '../styles/globals.css';
import { playfair, openSans } from '@/fonts/fonts';

import Header from '@/components/shared/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={`${playfair.variable} ${openSans.variable}`}
    >
      <body className='pt-16'>
        <Header />
        <main className='px-8'>{children}</main>
      </body>
    </html>
  );
}
